# List of puns that Puninator can spit out.

puns = [
    "What happens when frogs park illegally?\nThey get toad.",
    "What do you call it when a midget waves at you?\nA microwave.",
    "You hear about the guy who lost the left side of his body?\nHe's all right now.",
    "The graveyard is the most popular place on Earth.\nPeople are dying to get in there.",
    "A cardboard belt is a waist of paper.",
    "I ate a watch once.\nIt was time consuming.",
    "I made a belt out of watches once.\nIt was a waist of time.",
    "My neighbor has two dogs named Rolex and Timex.\nThey're watch dogs.",
    "What's Forrest Gump's password?\n1Forrest1.",
    "Rest in peace, boiling water.\nYou will be mist.",
    "I lost my job at the bank on the first day.\nA lady asked me to check her balance, so I pushed her over.",
    "I got hit in the head with a can of soda yesterday.\nLuckily it was a soft drink.",
    "Why did the can-crusher quit his job?\nBecause it was soda-pressing.",
    "I have many jokes about unemployed people.\nSadly, none of them work.",
    "A guitar teacher got arrested for fingering a minor.",
    "Confucius says: man who runs behind car will get exhausted,\nbut man who runs in front of car will get tired.",
    "Why doesn't the Sun go to college?\nBecause it has a million degrees.",
    "I accidentally drank some food coloring yesterday.\nI dyed a little inside.",
    "I tried to sue the airport for misplacing my luggage.\nI lost my case.",
    "I entered ten puns into a contest to see which one would win.\nNo pun in ten did.",
    "I was fired from the clock factory for the extra hours I put in.",
    "It'd be awesome if mannequins had bigger breasts, wooden tit?",
    "There was a kidnapping at school.\nDon't worry, he woke up.",
    "My cow wandered into a field of Marijuana.\nThe steaks have never been so high.",
    "I have a fear of speed bumps.\nI'm slowly getting over it, though.",
    "How do you cut Rome in half?\nWith a pair of Caesars.",
    "What do you call a hundred rabbits walking backwards?\nA receding hare line.",
    "A prisoner was told how he'd be executed.\nNeedless to say, he was shocked.",
    "How does Moses prepare his tea?\nHebrews it.",
    "Why were the Middle Ages called the Dark Ages?\nBecause there were too many knights.",
    "What's the best thing about living in Switzerland?\nI don't know, but the flag is a big plus.",
    "The past, the present and the future walked into a bar.\nIt was tense.",
    "Some people think 'prison' is one word.\nBut for robbers, it's a whole sentence.",
    "Is the pool safe for driving?\nIt deep ends.",
    "I saw a documentary about beavers.\nIt was the best dam program I've ever seen.",
    "How do you steal a coat?\nYou jacket.",
    "How do you organize a space party?\nYou planet.",
    "Yesterday, a clown held a door open for me.\nIt was a nice jester.",
    "I couldn't get a reservation at the library.\nThey were completely booked.",
    "I used to work in a shoe recycling shop.\nIt was sole destroying.",
    "I used to hate facial hair, but then it grew on me.",
    "Why did the stadium get hot after the game?\nBecause all the fans left.",
    "I went on a date last night with a girl from the zoo.\nIt was great. She's a keeper.",
    "I have the heart of a lion.\nAnd a lifetime ban from the San Diego Zoo.",
    "Why are ducks such great detectives?\nThey always quack the case.",
    "What's the difference between a hippo and a Zippo?\nOne is heavy, the other is a little lighter.",
    "I cut my finger chopping cheese, but I think I have grater problems.",
    "Atheism is a non-prophet organization.",
    "What is a tornado's favorite game?\nTwister.",
    "What do soldiers call their morning coffee?\nG.I. joe.",
    "Don't let the cops ketchup to you.",
    "Why do dinosaurs smell so much?\nBecause they're ex-stinkt.",
    "Why do cows have hooves instead of feet?\nBecause they lactose.",
    "I hate how funerals are always at 9am.\nI'm not really a mourning person.",
    "Claustrophobic people are more productive thinking out of the box.",
    "My ex-wife still misses me.\nBut her aim is steadily improving.",
    "I couldn't remember how to throw a boomerang.\nEventually, though, it came back to me.",
    "How do trees get online?\nThey just log in.",
    "Someone stole my toilet and the police have nothing to go on.",
    "Two artists had an art contest.\nIt ended in a draw.",
    "What do you call an alligator in a vest?\nAn investigator.",
    "Communist jokes aren't funny unless everyone gets them.",
    "What do you call a nose without a body?\nNobody knows.",
    "Have you heard about the movie Constipation?\nIt hasn't come out yet.",
    "Velcro is a total rip-off.",
    "What do you call a Russian tree?\nDimitree.",
    "I used to be a banker, but I lost interest.",
    "I was very lonely, so I bought some shares.\nIt's nice to have a bit of company.",
    "Two deer walk out of a gay bar.\nOne says to the other: 'I can't believe I blew forty bucks in there.'",
    "Want some dead batteries?\nThey're free of charge.",
    "I started a band named 999 Megabytes.\nWe still haven't gotten a gig.",
    "Did you know that towels are the leading cause of dry skin?",
    "If trees could kill you, they wood.",
    "How did the hipster burn his tongue?\nHe drank his coffee before it was cool.",
    "Will glass coffins be a success?\nRemains to be seen.",
    "I'm a big fan of whiteboards.\nThey're quite re-markable.",
    "What did the ocean say to the shore?\nNothing, it just waved.",
    "is it just me or are magnets really attractive?",
    "Why didn't the butcher cut the fillet?\nBecause it was a misteak.",
    "If there was someone selling drugs here, weed know.",
    "Why don't skeletons take risks?\nBecause they have no guts.",
    "I don't know why the furniture store keeps calling me back.\nAll I wanted was that one nightstand.",
    "Did you hear that rumor about butter?\nNevermind, I shouldn't spread it.",
    "Why did the coffee go to the police?\nBecause it was mugged.",
    "What do you call a cow jumping over barbed wire?\nUdder destruction.",
    "Why didn't the bike stand on its own?\nIt was two tired.",
    "Why didn't the toilet paper cross the road?\nIt was stuck in a crack.",
    "You hear about the blind man who fell down a well?\nHe couldn't see that well.",
    "What do you get if you throw a piano down a mine shaft?\nA flat miner.",
    "My friend told me that pepper is the best seasoning for a roast.\nI took it with a grain of salt.",
    "Did you hear about the Italian chef?\nHe pasta-way.",
    "Want to hear a joke about paper?\nNevermind, it's tearable.",
    "How does a penguin build its house?\nIgloos it together.",
    "A local scarecrow got an award for being out standing in its field."]

